Check there was no bundling with cdk-booster

diff --git a/.github/workflows/common-test.yml b/.github/workflows/common-test.yml
--- a/.github/workflows/common-test.yml
+++ b/.github/workflows/common-test.yml
@@ -71,8 +71,14 @@ jobs:
       - name: Deploy CDK original
         run: |
           npx tsx ../../scripts/modify-cdk-json.ts ../../test/cdk-basic/cdk.json "npx ts-node --prefer-ts-exts bin/cdk-basic.ts"
-          npm run deploy
+          npm run deploy | tee cdk-original.log
         working-directory: test/cdk-basic
+      - name: Check there was bundling
+        run: |
+          if ! grep -q "Bundling asset" cdk-original.log; then
+            echo "ERROR: Expected 'Bundling asset' not found in logs."
+            exit 1
+          fi
       - name: Save CDK original state
         run: |
           npx tsx ../../scripts/export-state.ts cdk-outputs.json cdk-original-function-files.json
@@ -80,8 +86,14 @@ jobs:
       - name: Deploy via cdk-booster
         run: |
           npx tsx ../../scripts/modify-cdk-json.ts ../../test/cdk-basic/cdk.json "node ../../dist/cdkbooster.mjs bin/cdk-basic.ts"
-          npm run deploy
+          npm run deploy | tee cdk-booster.log
         working-directory: test/cdk-basic
+      - name: Check there was no bundling
+        run: |
+          if grep -q "Bundling asset" cdk-booster.log; then
+            echo "ERROR: Unexpected 'Bundling asset' found in logs."
+            exit 1
+          fi
       - name: Save cdk-booster state
         run: |
           npx tsx ../../scripts/export-state.ts cdk-outputs.json cdk-booster-function-files.json
